backup

diff --git a/.dotfiles/scripts/docs b/.dotfiles/scripts/docs
--- a/.dotfiles/scripts/docs
+++ b/.dotfiles/scripts/docs
@@ -1,36 +1,48 @@
 #!/usr/bin/env sh
-# Select docs from devdocs.io using a fuzzy-finder for display at the CLI
+# Usage:
+#     prog_name                    - Show docset picker and show docs for selected docset
+#     prog_name <docset>           - Show docs for <docset>
+#     prog_name <command>          - Show docset picker and execute <command>
+#     prog_name <command> <docset> - Execute <command> for <docset>
 #
+# Notes:
+#     <command> - must be a full command name
+#     <docset>  - can be a partial name and will be fuzzy matched
+#
+# Options:
+#     -h, --help  - This help information
+#     -c, --check - Check if script can be succesfully ran
+#
+# Commands:
+#     get         - Download new docset
+#     regen       - Regenerate pages for docset
+#     purge       - Delete docset
+#     check       - Same as --check flag
+#     help        - Same as --help flag
+#
+
+# Select docs from devdocs.io using a fuzzy-finder for display at the CLI
 # Deps: tidy, xmlstarlet, jq, lynx, fzy, curl, POSIX, lr (leahneukirchen)
 # (This uses a few shell scripts from $HOME/bin. Look there for reference.)
-#
-# Download docsets:
-#
-#     devdocs get
-#     devdocs get lodash~4 rxjs
-#     devdocs get_from /path/to/devdocs-prefs-export.json
-#
-# Query downloaded docsets:
-#
-#     devdocs
-#     devdocs "language"
-#
-# Regenerate cached pages:
-#
-#     devdocs regen
-#
 
 NAME=$(basename "$0")
 TEMP="${TMPDIR-/tmp}/${NAME}.${$}.$(awk \
     'BEGIN {srand(); printf "%d\n", rand() * 10^10}')"
 
+__has() {
+    command -v $@ 2>&1 >/dev/null && return 0 || return 1
+}
+
+browser=lynx
+__has w3m && browser=w3m
+__has elinks && browser=elinks
+
 init_cache_dir() {
     mkdir -p "$DEVDOCS_DIR"
     node_idx="$DEVDOCS_DIR/index.js"
     node_pkg="$DEVDOCS_DIR/package.json"
-    node_fof="$DEVDOCS_DIR/404.html"
-    idx_js='
-const express = require("express");
+
+    idx_js='const express = require("express");
 const path = require("path");
 const fs = require("fs");
 
@@ -50,7 +62,7 @@ app.all("*", (req, res) => {
     }
 });
 
-const port = process.env.PORT || 8080;
+const port = process.env.PORT || 2517;
 
 app.listen(port, (err, res) => {
     if (err) {
@@ -61,10 +73,9 @@ app.listen(port, (err, res) => {
     }
 });
 
-module.exports = app;
-'
-    package_json='
-{
+module.exports = app; '
+
+    package_json='{
   "name": "devdocs-local",
   "version": "1.0.0",
   "main": "index.js",
@@ -77,17 +88,15 @@ module.exports = app;
   "dependencies": {
     "express": "^4.21.1"
   }
-}
-'
+} '
 
     echo "$idx_js" > "$node_idx"
     echo "$package_json" > "$node_pkg"
-    echo "<h1>404 Specified page not found</h1>" > "$node_fof"
 
     npm install --prefix "$DEVDOCS_DIR"
 }
 
-[ -n "$DEVDOCS_DIR" ] && DEVDOCS_DIR="$XDG_DATA_HOME/devdocs"
+[ ! -n "$DEVDOCS_DIR" ] && DEVDOCS_DIR="$XDG_DATA_HOME/devdocs"
 [ "$DEVDOCS_DIR" = "/devdocs" ] && DEVDOCS_DIR="$HOME/.local/share/devdocs"
 [ ! -d "$DEVDOCS_DIR" ] && init_cache_dir
 
@@ -98,6 +107,7 @@ list() {
 }
 
 gen_pages() {
+    [ ! -n "$@" ] && exit 1
     slug="$@"
     lang_dir="${DEVDOCS_DIR}/${slug}"
 
@@ -106,7 +116,11 @@ gen_pages() {
     [ -d "${lang_dir}/pages" ] && rm -rf "${lang_dir}/pages"
     mkdir -p "${lang_dir}/pages"
 
-    jq -r '.entries[] | "\(.path)"' "${lang_dir}/index.json" | while read line; do
+    page_list="$(jq -r '.entries[] | "\(.path)"' "${lang_dir}/index.json")"
+    page_count=$(echo "$page_list" | wc -l)
+    current_page=1
+
+    echo "$page_list" | while read line; do
         page="$(echo -e "$line" | cut -d "#" -f 1)"
         if [[ "$line" == *"#"* ]]; then
             if ! ( [[ "$(basename "$page")" == "index" ]] && [[ $did_index -eq 0 ]] ); then
@@ -123,19 +137,21 @@ gen_pages() {
         if ! [[ "$page" == *".html" || "$page" == *".xhtml" ]]; then
             page="$page.html"
         fi
-        echo "Writing ${page}"
+        echo "[$current_page/$page_count] Writing ${page}"
         jq -r ".\"${idx}\"" \
             <"${lang_dir}/db.json" \
             >"${lang_dir}/pages/${page}"
 
         printf "\033[1A\033[K"
+        ((++current_page))
     done
     echo "Finished generating pages for ${slug}"
 }
 
 regen() {
     lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' |
-        gen_pages "$(fzy -p 'Choose docs > ')"
+        gen_pages "$(fzf --layout="reverse" --height=35% --prompt="Choose docs > " -0 -q "$@")"
+        # gen_pages "$(fzy -p 'Choose docs > ')"
 
 }
 
@@ -175,34 +191,44 @@ download() {
 }
 
 get() {
-    if [ $# -eq 0 ]; then
-        list | fzy -p 'Choose a docset > ' | download
-    else
-        list | awk '
-            BEGIN {
-                for (i = 1; i < length(ARGV); i += 1) {
-                    docs[ARGV[i]] = 1; ARGV[i] = ""
-                }
-            }
+    list | fzf --layout="reverse" --height=35% --prompt="Choose a docset > " -0 -q "$@" | download
+    # if [ $# -eq 0 ]; then
+    #     # list | fzf --layout="reverse" --height=35% --prompt="Choose a docset > " -0 -q "$@" | download
+    #     # list | fzy -p 'Choose a docset > ' | download
+    # else
+    #     list | awk '
+    #         BEGIN {
+    #             for (i = 1; i < length(ARGV); i += 1) {
+    #                 docs[ARGV[i]] = 1; ARGV[i] = ""
+    #             }
+    #         }
 
-            docs[$1] { print $0 }
-        ' "$@" | download
-    fi
+    #         docs[$1] { print $0 }
+    #     ' "$@" | download
+    # fi
 }
 
-get_from() {
-    jq -r '.docs | split("/")[]' "${1:?Missing Devdocs Prefs export JSON}" |
-        xe -N0 "$0" choose
-}
+# get_from() {
+#     jq -r '.docs | split("/")[]' "${1:?Missing Devdocs Prefs export JSON}" |
+#         xe -N0 "$0" choose
+# }
 
 doc_for() {
     echo "$@" | {
         read -r slug
         test -n "$slug" || return
 
+        if [ ! -d "$DEVDOCS_DIR/$slug" ]; then
+            dirs="$(lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' -t 'name != "node_modules"')"
+            lang="$(echo "$dirs" | fzf --layout="reverse" --height=35% --prompt="Choose docs > " -1 -0 -q "$slug")"
+            [ ! -n "$lang" ] && exit 1
+            slug="$lang"
+        fi
+
         jq -r '.entries[] | "\(.name) --- \(.path) --- (\(.type))"' \
             "${DEVDOCS_DIR}/${slug}/index.json" |
-            fzy -p 'Choose a topic > ' |
+            fzf --layout="reverse" --height=35% --prompt="Chose a topic > " |
+            # fzy -p 'Choose a topic > ' |
             awk -F " --- " '{
                 h = index($2, "#")
                 if (h == 0) {
@@ -221,11 +247,11 @@ doc_for() {
             # screen -d -m http-server "${DEVDOCS_DIR}/${slug}/pages/" &
             screen -d -m npm run --prefix="$DEVDOCS_DIR" serve &
 
-            sleep 0.25
+            sleep 0.35
 
             # lynx -assume_charset=utf-8 \
-            w3m -I=utf-8 \
-                "http://127.0.0.1:8080/${slug}/pages/${dpath}${frag}"
+            $browser \
+                "http://127.0.0.1:2517/${slug}/pages/${dpath}${frag}"
             # lynx -assume_charset=utf-8 \
             #     "file://localhost/${DEVDOCS_DIR}/${slug}/pages/${dpath}.html${frag}"
 
@@ -237,19 +263,42 @@ doc_for() {
 
 doc() {
     lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' -t 'name != "node_modules"' |
-        doc_for "$(fzy -p 'Choose docs > ')"
+        doc_for "$(fzf --layout="reverse" --height=35% --prompt="Choose docs > ")"
+        # doc_for "$(fzy -p 'Choose docs > ')"
+}
+
+purge() {
+    lang=""
+    dirs="$(lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' -t 'name != "node_modules"')"
+    lang="$(echo "$dirs" | fzf --layout="reverse" --height=35% --prompt="Choose docs > " -0 -q "$@")"
+    doc_dir="$DEVDOCS_DIR/$lang"
+    [ ! -n "$lang" ] && exit 1
+    echo "Selected '$lang' language"
+    if [ -d "$doc_dir" ]; then
+        gum confirm "Are you sure?" --default=false && rm -rf "$doc_dir" || echo "Cancelling"
+    fi
+}
+
+print_help() {
+    awk 'NR == 1 { next } /^$/ { exit } { print substr($0, 3) }' "$0" | sed "s#prog_name#$(basename "$0")#"
+    exit 0
+}
+
+check_health() {
+    echo "Missing programs:"
+    __has awk    || echo "    awk"
+    __has sed    || echo "    sed"
+    __has fzf    || echo "    fzf"
+    __has jq     || echo "    jq"
+    __has lr     || echo "    lr"
+    __has npm    || echo "    npm"
+    __has node   || echo "    node"
+    __has curl   || echo "    curl"
+    __has screen || echo "    screen"
+    __has $browser || echo "    missing browser (lynx > w3m > elinks)"
 }
 
 main() {
-    # shows help message
-    while getopts h opt; do
-        case $opt in
-        h)
-            awk 'NR == 1 { next } /^$/ { exit } { print substr($0, 3) }' "$0"
-            exit
-            ;;
-        esac
-    done
     # shift program out?
     shift $((OPTIND - 1))
 
@@ -262,23 +311,30 @@ main() {
 
     if [ $# -eq 0 ]; then
         doc
-    elif [ "$@" = "get" ]; then
-        get
-    elif [ "$@" = "get_from" ]; then
-        get_from
-    elif [ "$@" = "list" ]; then
-        list
-    elif [ "$@" = "regen" ]; then
-        regen
-    elif [ "$@" = "reinit_cache_dir" ]; then
+    elif [[ "$1" == "--help" || "$1" == "-h" || "$1" == "help" ]]; then
+        print_help
+    elif [[ "$1" == "--check" || "$1" == "-c" || "$1" == "check" ]]; then
+        check_health
+    elif [ "$1" = "get" ]; then
+        shift
+        get "$@ "
+    # elif [ "$1" = "get_from" ]; then
+    #     shift
+    #     get_from "$@"
+    # elif [ "$1" = "list" ]; then
+    #     list
+    elif [ "$1" = "regen" ]; then
+        shift
+        regen "$@ "
+    elif [ "$1" = "purge" ]; then
+        shift
+        purge "$@ "
+    elif [ "$1" = "reinit_cache_dir" ]; then
         init_cache_dir
     else
-        lang=$1
-        shift
-
-        # "$cmd" "$@"
-        doc_for "$lang"
+        doc_for "$@ "
     fi
 }
 
 main "$@"
+
